version: "3.8"

services:
    # Contenedor de Base de Datos MongoDB
    bdpractica4:
        image: mongo
        restart: always
        container_name: bdpractica4
        volumes:
            - type: volume
              source: practica4-mongo-volume
              target: /data/db
        ports:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
            MONGO_INITDB_DATABASE: ${MONGO_NAME}
        networks:
            - db_network
    # Contenedores de Server API 
    server1:
        build: ./serverAPI/
        container_name: server1
        ports:
            - "${PORT_SERVERS}"
        volumes:
            - type: bind
              source: ./serverAPI/src
              target: /code/src
        environment:
            USER_DB: ${MONGO_USER}
            PASS_DB: ${MONGO_PASS}
            NAME_DB: ${MONGO_NAME}  
            SERVER_DB: bdpractica4
            PORT_DB: 27017            # Puerto por defecto de MongoDB
            PORT_API: ${PORT_SERVERS} # Puerto donde se levanta los web services
            ID_API: ${SERVER1_ID}
        networks: 
            - service_network
            - db_network
    server2:
        build: ./serverAPI/
        container_name: server2
        ports:
            - "${PORT_SERVERS}"
        volumes:
            - type: bind
              source: ./serverAPI/src
              target: /code/src
        environment:
            USER_DB: ${MONGO_USER}
            PASS_DB: ${MONGO_PASS}
            NAME_DB: ${MONGO_NAME}  
            SERVER_DB: bdpractica4
            PORT_DB: 27017            # Puerto por defecto de MongoDB
            PORT_API: ${PORT_SERVERS} # Puerto donde se levanta los web services
            ID_API: ${SERVER2_ID}
        networks: 
            - service_network
            - db_network
    server3:
        build: ./serverAPI/
        container_name: server3
        ports:
            - "${PORT_SERVERS}"
        volumes:
            - type: bind
              source: ./serverAPI/src
              target: /code/src
        environment:
            USER_DB: ${MONGO_USER}
            PASS_DB: ${MONGO_PASS}
            NAME_DB: ${MONGO_NAME}  
            SERVER_DB: bdpractica4
            PORT_DB: 27017            # Puerto por defecto de MongoDB
            PORT_API: ${PORT_SERVERS} # Puerto donde se levanta los web services
            ID_API: ${SERVER3_ID}
        networks: 
            - service_network
            - db_network
    # Contenedor de Nginx
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
          - ./loadBalancer/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - server1
          - server2
          - server3
        ports:
          - "${PORT_BALANCER}"
        networks:
          - service_network
    # Contenedor de Nginx
    frontend:
        build: ./frontend/
        container_name: frontend
        ports:
            - "${PORT_FRONTEND}"
        volumes:
            - type: bind
              source: ./frontend/src
              target: /code/src
        environment:
            PORT_BALANCER: ${PORT_BALANCER}
            SERVER_BALANCER: nginx
            PORT_FRONTEND: ${PORT_FRONTEND} # Puerto donde se levanta el frontend
        networks: 
            - service_network
            - frontend_network
    frontendng:
        build: ./frontng/
        container_name: frontendng
        volumes:
          - ./frontng/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - nginx
        ports:
          - "${PORT_FRONTEND}:${PORT_FRONTEND}"
        networks:
          - service_network
          - frontend_network
networks: 
    db_network:
        driver: bridge
    service_network:
        driver: bridge
    frontend_network:
        driver: bridge
volumes:
    practica4-mongo-volume: