version: "3.8"

services:
    # Contenedor de Base de Datos MongoDB
 bdproyecto:
  image: mongo
  restart: always
  container_name: bdpractica4
  volumes:
   - type: volume
     source: practica4-mongo-volume
     target: /data/db
  ports:
   - "27017"
  network_mode: "host"
  environment:
   MONGO_INITDB_ROOT_USERNAME: admin   
   MONGO_INITDB_ROOT_PASSWORD: admin
   MONGO_INITDB_DATABASE: bdpractica4
volumes:
 practica4-mongo-volume: