version: "3.8"

services:
 api2:
  build: ./
  container_name: api2
  ports:
   - "1000:1000"
  network_mode: "host"
  volumes:
   - type: bind
     source: ./src
     target: /code/src
  environment:
   PORT_API: 1000
   ID_API: API__2
   IP_SERVER: localhost
   PORT_SERVER: 5000

