version: "3.8"

services:
  	loadbalancer:
        build: ./
        container_name: loadbalancer
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - nginx
        ports:
          - 5000:5000