version: "3.8"

services:
 servidor2:
  build: ./
  container_name: servidor2
  ports:
   - "6000:6000"
  network_mode: "host"
  volumes:
   - type: bind
     source: ./src
     target: /code/src
  environment:
   SERVER_ID: servidor2
   SERVER_PORT: 6000
   USER_DB: admin
   PASS_DB: admin
   SERVER_DB: 50.0.30.134



