version: "3.8"

services:
    # Contenedor de Base de Datos MongoDB
 bdproyecto:
  image: mongo
  restart: always
  container_name: bdproyecto
  volumes:
   - type: volume
     source: proyeto-mongo-volume
     target: /data/db
  ports:
   - "27017:27017"
  network_mode: "host"
  environment:
   MONGO_INITDB_ROOT_USERNAME: admin   
   MONGO_INITDB_ROOT_PASSWORD: admin
   MONGO_INITDB_DATABASE: bdproyecto
 mongo-express-usuarios:
  image: mongo-express
  container_name: mongo-express-usuarios
  restart: always
  ports:
   - "8081:8081"
  network_mode: "host"
  environment:
   ME_CONFIG_MONGODB_SERVER: 127.0.0.1
   ME_CONFIG_MONGODB_PORT: 27017
   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
   ME_CONFIG_MONGODB_ADMINPASSWORD: admin
volumes:
 proyeto-mongo-volume: